### ISSUE TITLE
Could you please provide the dataset?

### ISSUE THREAD

**Issue by WanMingfei** [UMich-CURLY/drift#14]
Thank you for sharing your code and examples. They are very helpful for my research/project. I am trying to run your code, but I noticed that the dataset needed to execute the examples is not included in the repository.

Could you please provide the dataset or let me know where I can access it? This would greatly help me in understanding and replicating your work.

Thank you for your assistance.

**Comment by tzuyuan** [comment]
Hi!

Sure. Here's the Fetch dataset that we used: 
https://www.dropbox.com/scl/fo/bbhz9iuzowjr7y5un22cx/h?rlkey=cvq2uji28bm91gxwx8i4por3i&dl=0

I'm traveling for conferences now so I don't have other data by my side, but I'll try to upload them when I return to the office.

**Comment by tzuyuan** [comment]
Here's the Husky data:
https://www.dropbox.com/scl/fo/gsov30z7pjyonptbbvj7f/APVxWcYlNRaXhYp7DReyQXE?rlkey=abmnsr736n0oft906nbxpq11i&st=oh5uifzr&dl=0
