### ISSUE TITLE
How to handle if the position of CoM is different from the position of IMU

### ISSUE THREAD

**Issue by hxydebug** [UMich-CURLY/drift#15]
My robot's IMU frame is different from CoM frame, and my kinematics is from CoM to foot. So what should I do to make the inEKF work if the position of CoM is different from the position of IMU?

**Comment by tzuyuan** [comment]
Hi,

You can change the `rotation_imu2body` in `config/robot/imu_propagation` when the body frame (or CoM) is not aligned with the IMU. The IMU measurements will be transformed by this transformation before propagation.
